// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageService.proto

package com.openbytecode.rpc.core.grpc.proto;

public interface MessageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.pro.message.pipe.core.grpc.proto.MessageRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string body = 1;</code>
   * @return The body.
   */
  String getBody();
  /**
   * <code>string body = 1;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
