// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageService.proto

package com.openbytecode.rpc.core.grpc.proto;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pro_message_pipe_core_grpc_MessageRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pro_message_pipe_core_grpc_MessageRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_pro_message_pipe_core_grpc_MessageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_pro_message_pipe_core_grpc_MessageResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024MessageService.proto\022\036com.pro.message." +
      "pipe.core.grpc\"\036\n\016MessageRequest\022\014\n\004body" +
      "\030\001 \001(\t\"\037\n\017MessageResponse\022\014\n\004body\030\001 \001(\t2" +
      "\206\001\n\016MessageService\022t\n\021messageProcessing\022" +
      "..com.pro.message.pipe.core.grpc.Message" +
      "Request\032/.com.pro.message.pipe.core.grpc" +
      ".MessageResponseB\020B\014MessageProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_pro_message_pipe_core_grpc_MessageRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_pro_message_pipe_core_grpc_MessageRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pro_message_pipe_core_grpc_MessageRequest_descriptor,
        new String[] { "Body", });
    internal_static_com_pro_message_pipe_core_grpc_MessageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_pro_message_pipe_core_grpc_MessageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_pro_message_pipe_core_grpc_MessageResponse_descriptor,
        new String[] { "Body", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
